### ISSUE TITLE
Doesn't work anymore with the new Integration

### ISSUE THREAD

**Issue by teranus** [Szaki-dev/tuya_fix#2]
Hello
I installed your fix this morning and since then my Tuya integration is broken.
I have the feeling that it's related to the update of the auth-methode since HA core 2024.3.1
Obviously I need to delete the integration, then the fix and install again the Tuya integration without the fix

Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 1 April 2024 at 10:26:17 (2 occurrences)
Last logged: 1 April 2024 at 10:28:42

Error setting up entry tera@teranus.de for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya/__init__.py", line 63, in async_setup_entry
    auth_type = AuthType(entry.data[CONF_AUTH_TYPE])
                         ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'auth_type'

**Comment by Szaki-dev** [comment]
Hi, thank you for the information, the new version should work now. If you have issues with the devices still, try unlinking then relinking your tuya account.
